- name: 📂 Sync files to FTP
  uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  with:
    server: zouljore.com
    username: chantiers
    password: ${{ secrets.FTP_PROD }}
    protocol: ftp
    port: 21
    server-dir: /public_html/
    local-dir: ./ 
    passive: true
    timeout: 60000
    exclude: |
      **/.git*
      **/.github*
      **/node_modules/**
      **/*.yml